### ISSUE TITLE
crouton-rgb-slider - bars self updating

### ISSUE THREAD

**Issue by wickwire** [edfungus/Crouton#11]
Hi,

I just noticed that the rgb slider component has some issues, when I update one bar, the other ones sometimes auto-update as well. I'll have a look at it whenever I can.

**Comment by jakeloggins** [comment]
I had a problem with this on the device end. The dashboard was sending messages faster than the esp8266 could handle them. So the device would update, miss a few commands, then send back a confirmation from a few values ago. So the bar on the dashboard would slide backward. If I did it too quickly with multiple bars I would get the same behavior you described.

My workaround is for the device to ignore commands from the dashboard if not enough time has elapsed, right now that's set at 200ms.
