### ISSUE TITLE
A way to define default connection on the server side

### ISSUE THREAD

**Issue by post2web** [edfungus/Crouton#19]
What would be the right way to create default mqtt connection on from sever?

**Comment by edfungus** [comment]
Can you explain a little more. Did you want to change the default broker address to something other than _test.mosquitto.org_?

**Comment by post2web** [comment]
I want to change the default connection settings to something other than test.mosquitto.org.

**Comment by edfungus** [comment]
If you look at the [crouton-frame element](https://github.com/edfungus/Crouton/blob/a62cab527a42e06a7e759d8a1ee228648eb34c80/public/app/framework/crouton-frame/crouton-frame.pug) at line 36, it is declaring a crouton-connect-mqtt element with the default address and port as attributes. If you change those, then the default connection settings will be changed.
