### ISSUE TITLE
not working on raspberry pi

### ISSUE THREAD

**Issue by kugala** [edfungus/Crouton#20]
Hi, there!
Installed Crouton on a Raspberry Pi 3 and was able to start.
Message was "Crouton started at http://localhost:8080", but browsing the url no content was displayed.
Any suggestion ?
When it will work it's a great job.
Thx!

**Comment by edfungus** [comment]
Can you try `bower install` too and then see if you see anything? Also are there any errors in the developer tool console?

**Comment by kugala** [comment]
OK!
thank's - found the solution in closed issue "white page"
have to start with grunt !
great work - thank you
