### ISSUE TITLE
grunt cpu use in Raspberry Pi

### ISSUE THREAD

**Issue by gerardovf** [edfungus/Crouton#21]
I found that grunt was taking more than 90% cpu.
After some Google search I was able to solve it adding a 2 seconds 'interval' option in the "gruntfile.js" file:
    watch: {
      styles: {
        files: [
          'public'
        ],
        tasks: ['less', 'pug', 'sync', 'clean'],
        options: {
          livereload: true,
          nospawn: true
        }
      },
      **_options: {
        interval: 2000_**
      }

**Comment by edfungus** [comment]
I made commit 8a0c67b6f18a8107667157720425900df3a234 like above. Thanks for the suggestion!
