### ISSUE TITLE
The three check boxes in connections page are not shown

### ISSUE THREAD

**Issue by gerardovf** [edfungus/Crouton#24]
In page http://crouton.mybluemix.net/crouton/connections the three check boxes  ("Auto-connect","Save username/password (warning: in plaintext)","Secure Websockets (TLS)") are shown.
When using the Crouton code from the Github in my Raspberry Pi they disappear.

Maybe it has to do with the Polymer version?

Screenshots and Html differences I found on the checkboxes section: 

![connectionspagebluemix](https://cloud.githubusercontent.com/assets/21976915/19106477/cfce2f8c-8ae7-11e6-9b79-b08d793ebf8a.jpg)
![connectionspagegvf1](https://cloud.githubusercontent.com/assets/21976915/19106879/e98b3a58-8ae9-11e6-854b-cf9dbb0bf19c.jpg)

[HtmlGvf1.txt](https://github.com/edfungus/Crouton/files/510473/HtmlGvf1.txt)
[HtmlEdfungus1.txt](https://github.com/edfungus/Crouton/files/510472/HtmlEdfungus1.txt)

**Comment by wickwire** [comment]
It's possible, I'm getting improper formatting on my checkboxes too, not applying the line breaks and the teal colour styling.

My guess is that either Polymer or some other dependency upgraded in a way that broke the styling... I will post here if I find anything.

**Comment by wickwire** [comment]
In file **public/app/framework/crouton-card/crouton-card.less**

Does changing class **paper-checkbox.paper-checkbox-0** to **paper-checkbox.paper-checkbox-1** fix the issue for you?

**Comment by gerardovf** [comment]
You're right! Now the checkboxes are shown. **BUT** the texts on the right are still not shown. :-(

**Comment by wickwire** [comment]
Which polymer version did you choose at nom install?

**Comment by wickwire** [comment]
Try checking out my fork from scratch and choosing resolves to polymer 1.7.0 (like option 8)

**Comment by gerardovf** [comment]
I will. The values I see in the default "bower.json" file:
    "font-roboto": "PolymerElements/font-roboto#^1.0.1",
    "iron-a11y-announcer": "PolymerElements/iron-a11y-announcer#^1.0.0",
    "iron-a11y-keys-behavior": "polymerelements/iron-a11y-keys-behavior#^1.0.0",
    "iron-autogrow-textarea": "PolymerElements/iron-autogrow-textarea#^1.0.0",
    "iron-ajax": "PolymerElements/iron-ajax#^1.0.0",
    "iron-checked-element-behavior": "PolymerElements/iron-checked-element-behavior#^1.0.0",
    "iron-collapse": "PolymerElements/iron-collapse#^1.0.0",
    "iron-dropdown": "PolymerElements/iron-dropdown#^1.0.0",
    "iron-form": "PolymerElements/iron-form",
    "iron-image": "PolymerElements/iron-image#^1.2.0",
    "iron-media-query": "PolymerElements/iron-media-query#^1.0.0",
    "iron-input": "PolymerElements/iron-input#^1.0.0",
    "iron-menu-behavior": "PolymerElements/iron-menu-behavior#^1.0.0",
    "iron-range-behavior": "PolymerElements/iron-range-behavior#^1.0.0",
    "paper-behaviors": "PolymerElements/paper-behaviors#^1.0.0",
    "paper-button": "PolymerElements/paper-button",
    "paper-card": "PolymerElements/paper-card",
    "paper-checkbox": "PolymerElements/paper-checkbox",
    "paper-drawer-panel": "PolymerElements/paper-drawer-panel",
    "paper-dropdown-menu": "PolymerElements/paper-dropdown-menu",
    "paper-header-panel": "PolymerElements/paper-header-panel",
    "paper-fab": "PolymerElements/paper-fab",
    "paper-icon-button": "PolymerElements/paper-icon-button",
    "paper-item": "PolymerElements/paper-item",
    "paper-listbox": "polymerelements/paper-listbox",
    "paper-menu": "PolymerElements/paper-menu",
    "paper-progress": "PolymerElements/paper-progress#^1.0.0",
    "paper-slider": "PolymerElements/paper-slider",
    "paper-toast": "PolymerElements/paper-toast",
    "paper-toggle-button": "PolymerElements/paper-toggle-button",
    "polymer": "Polymer/polymer#~1.4.0"

**Comment by gerardovf** [comment]
wickwire, thanks a lot! That made the trick! I suppose in my first bower install dialog I chose an earlier polymer version. After checking that everything was ok with your fork from scratch I just deleted my previous "node_modules" and "build" directories, did 'npm install' and selected the last polymer version (option (8)

**Comment by wickwire** [comment]
Ok, just adding a note here: I will make a pull request from my fork to the original project, however this definitely seems like a Polymer upgrading issue. The current package files will offer the choice to the user, due to conflicting versions being used by several components. To be determined if there may be other components suffering from this or not, as well.
