### ISSUE TITLE
Bower Install Fails

### ISSUE THREAD

**Issue by lukasmartinelli** [edfungus/Crouton#27]
I am trying to build it locally but the `bower install` fails.

```
bower ECONFLICT Unable to find suitable version for polymer
```

**Comment by edfungus** [comment]
Hmm, I just ran it today and opted for polymer#^1.6.0 during the conflict. Maybe trying pulling master again and running `grunt`?

**Comment by mosheshp2** [comment]
see here: https://github.com/edfungus/Crouton/issues/28

try add to the bower.json the "resolutions": {
"polymer": "^1.1.0'
}

**Comment by XayOn** [comment]
I can confirm that works correctly.
