### ISSUE TITLE
manual for dummies?

### ISSUE THREAD

**Issue by josb86** [edfungus/Crouton#28]
Hi, A couple days I found this app but i can't get that this working, I have installed node.js anda know I am working with node-red and mqtt mosca, but with Crouton I don't even get star the app, the guie

  $ git clone https://github.com/edfungus/Crouton.git
  $ npm install
  $ grunt

Don´t work, You have any manual for dummies?

**Comment by mosheshp2** [comment]
It happend to me also, and I solved it by running the npm install on windows command line (CMD) and then it was "interactive console"
What eventually it added to the bower.json file is:
       ...
     "polymer": "Polymer/polymer#^1.2.0"
  }**,
  "resolutions": {
    "polymer": "^1.1.0"
  }**
}
at the end of the file.

**Comment by edfungus** [comment]
@mosheshp2, thanks. I added to the master branch
