### ISSUE TITLE
Crouton Does not connect to test.mosquitto.org

### ISSUE THREAD

**Issue by ghost** [edfungus/Crouton#32]
I have cloned your project and I have also used your website link(http://crouton.mybluemix.net/crouton/connections) to test Crouton and it won't even connect to test.mosquitto.org.

It just states connecting, then not connected?

**Comment by edfungus** [comment]
Just tried it and it works. To my understanding, the mosquitto servers are also their test servers and are not guaranteed to be up. Also if you are behind a proxy that could be blocking it too

**Comment by konstantinbarkalov** [comment]
Same for me, demo page does not work, it stucks at step 1.

Console:
> WebSocket connection to 'wss://test.mosquitto.org:8080/mqtt' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by ghost** [comment]
Yes, even from your own web site it doesn't connect:
Crouton

  
|  
|   |  
Crouton
   |  |

  |

**Comment by edfungus** [comment]
I tried it again today and I am getting the same issue you all are getting. I double checked on hivemq's online client (http://www.hivemq.com/demos/websocket-client/) with the same broker address and also can not connect.

I doubt this is a Crouton issue but rather the case that mosquitto's test servers are not reliably up. 

If there is an indication that this is a Crouton bug, please reopen or make another issue with the details. Thanks!
