### ISSUE TITLE
error on npm install

### ISSUE THREAD

**Issue by marco-palumbi** [edfungus/Crouton#35]
hello Edmund

I forked your repository some time ago and I was able to install and add some features that i needed.
some days ago i cloned again your repo but I got this error running npm install:

 ECONFLICT Unable to find suitable version for webcomponentsjs

is this a problem in my environment or there is a some change in the global dependencies that causes this issue?

**Comment by edfungus** [comment]
I think you mean issue with bower install? I don't think `npm install` downloads webcomponentsjs. Reference #37 for the bower issue
